---
# CI configuration
# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven
# https://github.com/actions/setup-java

name: Java CI

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 11.0.24
        - 21.0.5
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Build
      run: mvn --batch-mode --update-snapshots --show-version install


